spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

# TRACE, DEBUG, INFO, WARN, ERROR, FATAL, 'OFF' (quote OFF so it is interpreted as a String and not a boolean)
logging:
  level:
    root: INFO
    io:
      pivotal: INFO
    com:
      netflix: WARN
#        eureka: DEBUG #'OFF'
#        discovery: DEBUG #'OFF'
#      hystrix.AbstractCommand: DEBUG
#    org:
#      flywaydb: DEBUG
#        core.internal:
#          dbsupport.SqlScript: DEBUG # SQL only
#          command.DbMigrate: DEBUG

# Enable flyway
spring:
  jpa:
    hibernate:
      # ddl-auto: none
      # Validate the database schema according to the entities that in the application
      # Throws an error if the schema doesn’t match the entity specifications
      ddl-auto: validate
    # database: MYSQL
    ## Hibernate Properties
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect

##### spring.cloud.services.registrationMethod #####
# To change value of spring.cloud.services.registrationMethod to 
# "direct" (default is "route"), add "c2c" to active profiles

ribbon: # <---NEW SECTION
  IsSecure: false

#spring:
#  rabbitmq:
#    addresses: ${vcap.services.cloud-bus.credentials.http_api_uris:http://localhost:5672}
