management:
  security:
    enabled: false 
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

# TRACE, DEBUG, INFO, WARN, ERROR, FATAL, 'OFF' (quote OFF so it is interpreted as a String and not a boolean)
logging:
  level:
    root: FATAL 
    io:
      pivotal: DEBUG 
#    com:
#      netflix: ERROR
#        eureka: DEBUG #'OFF'
#        discovery: DEBUG #'OFF'
#      hystrix.AbstractCommand: DEBUG
#    org:
#      flywaydb: DEBUG
#        core.internal:
#          dbsupport.SqlScript: DEBUG # SQL only
#          command.DbMigrate: DEBUG

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
# Enable flyway
  jpa:
    hibernate:
      ddl-auto: validate
#      database: MYSQL
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#  rabbitmq:
#    addresses: ${vcap.services.cloud-bus.credentials.http_api_uris:http://localhost:5672}

ribbon: # <---NEW SECTION
  IsSecure: false
